name: CI

on:
  push:
  
jobs:

  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Github context
        run: echo '${{ toJSON(github) }}'

      - name: Echo
        run: exit 1