name: Runners Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Whether workflows is created or completed'
        required: true
        type: choice
        options:
        - created
        - completed

jobs:
  manage-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Github context
        run: echo '${{ toJSON(github) }}'
      
      - name: Execute Pulumi
        run: |
          case ${{ github.event.inputs.action }} in
            'created')
              action=up
              ;;
            'completed')
              action=down
              ;;
          esac
          echo $action