name: Runners Deployment

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types: 
#       - completed
#       - requested

jobs:
  manage-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Github context
        run: echo '${{ toJSON(github) }}'
      
      - name: Execute Pulumi
        run: |
          case ${{ github.event.action }} in
            'requested')
              action=up
              ;;
            'completed')
              action=down
              ;;
          esac
          echo $action